AWSTemplateFormatVersion: '2010-09-09'
Description: '(qs-1nltbq5f3) OpenShift+VPC, License: Apache 2.0 (Please do not remove)
  April, 6, 2018'
Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: DNS Configuration
        Parameters:
          - DomainName
          - HostedZoneID
          - SubDomainPrefix
          - CertificateArn
          - Route53HostedSubdomainZone
      - Label:
          default: Custom Resource Configuration
        Parameters:
          - ACMCertificateLambdaArn
    ParameterLabels:
      HostedZoneID:
        default: Route 53 Hosted Zone ID
      SubDomainPrefix:
        default: Subdomain Prefix
      CertificateArn:
        default: Certificate Arn
      DomainName:
        default: Domain Name
      Route53HostedSubdomainZone:
        default: Route 53 Subdomain Zone
Parameters:
  Route53HostedSubdomainZone:
    Type: String
  ACMCertificateLambdaArn:
    Type: String
  HostedZoneID:
    Description: 'OPTIONAL: Route 53 Hosted Zone ID to use. If left blank route 53
      will not be configured and DNS must be setup manually If you specify this you must also specify DomainName'
    Type: String
    MaxLength: '32'
    Default: ""
  CertificateArn:
    Description: 'OPTIONAL: Specify the arn of the certificate that will be presented.'
    Type: String
    Default: ""
  DomainName:
    Description: >-
      OPTIONAL: domain name configured for the cluster, if left blank self signed
      certificates will be used for TLS and the LoadBalancer's auto-generated hostname
      will be used for connections from outside the cluster.
    Type: String
    Default: ""
  SubDomainPrefix:
    Default: ''
    Description: 'OPTIONAL: Subdomain to use, if left blank DomainName will be used
      without a prefix. If you specify this you must also specify DomainName and HostedZoneID'
    Type: String

  ClusterName:
    Type: String

Resources:

  ACMCertificateDNS:
    Condition: UseDnsForACMValidation
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Ref 'ACMCertificateLambdaArn'
      HostedZoneId: !If
        - SetupSubdomain
        - !Ref 'Route53HostedSubdomainZone'
        - !Ref 'HostedZoneID'
      HostNames:
        - !Join
          - ''
          - - !If
              - UseSubdomain
              - !Sub '${SubDomainPrefix}.'
              - ''
            - !Ref 'DomainName'
        - !Join
          - ''
          - - '*.'
            - !If
              - UseSubdomain
              - !Sub '${SubDomainPrefix}.'
              - ''
            - !Ref 'DomainName'
        - !Join
          - ''
          - - '*.apps.'
            - !Sub '${ClusterName}.'
            - !If
              - UseSubdomain
              - !Sub '${SubDomainPrefix}.'
              - ''
            - !Ref 'DomainName'

  ACMCertificateEmail:
    Condition: UseEmailForACMValidation
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Join
        - ''
        - - !If
            - UseSubdomain
            - !Sub '${SubDomainPrefix}.'
            - ''
          - !Ref 'DomainName'
      SubjectAlternativeNames:
        - !Join
          - ''
          - - '*.'
            - !If
              - UseSubdomain
              - !Sub '${SubDomainPrefix}.'
              - ''
            - !Ref 'DomainName'
        - !Join
          - ''
          - - '*.apps.'
            - !Sub '${ClusterName}.'
            - !If
              - UseSubdomain
              - !Sub '${SubDomainPrefix}.'
              - ''
            - !Ref 'DomainName'
      DomainValidationOptions:
        - DomainName: !Join
            - ''
            - - !If
                - UseSubdomain
                - !Sub '${SubDomainPrefix}.'
                - ''
              - !Ref 'DomainName'
          ValidationDomain: !Ref 'DomainName'


Conditions:
  SetupRoute53: !And
    - !Not
      - !Equals
        - !Ref 'HostedZoneID'
        - ''
    - !Not
      - !Equals
        - !Ref 'DomainName'
        - ''
  SetupSubdomain: !And
    - !Not
      - !Equals
        - !Ref 'SubDomainPrefix'
        - ''
    - !Not
      - !Equals
        - !Ref 'HostedZoneID'
        - ''
    - !Not
      - !Equals
        - !Ref 'DomainName'
        - ''
  UseSubdomain: !Not
    - !Equals
      - !Ref 'SubDomainPrefix'
      - ''
  UseCustomCertificate: !Not
    - !Equals
      - !Ref 'CertificateArn'
      - ''
  UseEmailForACMValidation: !And
    - !Equals
      - !Ref 'HostedZoneID'
      - ''
    - !Not
      - !Equals
        - !Ref 'DomainName'
        - ''
    - !Not
      - Condition: UseCustomCertificate
  UseDnsForACMValidation: !And
    - Condition: SetupRoute53
    - !Not
      - Condition: UseCustomCertificate

Outputs:
  ACMCertificateDNSArn:
    Description: The ARN for the generated ACM Certificate
    Value: !GetAtt 'ACMCertificateDNS.Arn'
    Condition: UseDnsForACMValidation

  ACMCertificateEmail:
    Description: The ARN for the generated ACM Certificate
    Value: !Ref ACMCertificateEmail
    Condition: UseEmailForACMValidation
